### PR TITLE
helpers/get-glimmer: Fix behavior for "path = 0"

### PR DESCRIPTION
**Pull request by Turbo87**
This PR fixes issue #26

### CODE REVIEW

**Comment by Turbo87** [comment]
@jmurphyau any comments on this?

**Comment by jmurphyau** [comment]
Does this work in newer versions of ember that have the get helper built in? For some reason I believe the path must be a string and if your passing an integer it might throw an error.. 

I'll try have a look at this within the next day or two

**Comment by Turbo87** [comment]
I admit that I haven't tried it in the newer versions since I'm currently still targeting v1.13. I dont see for what reason the key must not be an integer though. I guess it might work if I explicitly convert the integers to strings first, but then again why not simply accept integers as well...

**Comment by Turbo87** [comment]
@jmurphyau the original implementation does indeed not support numbers here, it just shows nothing instead. I guess instead of my proposal here the addon implementation should actually check if the `path` is a string.

**Comment by Turbo87** [comment]
FWIW https://github.com/emberjs/ember.js/issues/13296

**Pull request closed without merging**
