### PR TITLE
Improve warnings and deprecations

### LINKED ISSUE #19: Wrong deprecation warning using Ember 1.13.10
With Ember 1.13.10, the helper beeing used is the glimmerHelper, but it throws this deprecation warning: 

`DEPRECATION: ember-get-helper has been included in Ember 2.0. Use of this package is deprecated` 

I wonder if this message could just be removed.
Unless I'm missing something, [this commit](https://github.com/jmurphyau/ember-get-helper/commit/718322682921772e717b37d5eaad3c7538625b30) the addon will just be a no op in 2.0, so the message would not be displayed anyway.

### LINKED ISSUE #22: Act as a polyfill
I think this project should behave a bit differently regarding ember versions.
We should follow [ember-new-computed](https://github.com/rwjblue/ember-new-computed)'s example and behave like:
> For versions prior to 1.12.0-beta.1 this addon will allow usage of the new syntax by polyfilling but as of Ember 1.12.0-beta.1 *a polyfill is not needed and the internal implementation of Ember.computed is used*.

This is extremely useful for addon developers that want to use the get helper in their addons but still want to maintain the compatibility with Ember 1.13 users.

### PR DESCRIPTION
**Pull request by jmurphyau**
Closes #22.
Closes #19.

### CODE REVIEW

**Comment by cibernox** [comment]
Is this ready to go? :bowtie:

**Comment by sly7-7** [comment]
:heart:

**Comment by jmurphyau** [comment]
v1.0.4 published - let me know how it goes

**Comment by rwjblue** [comment]
Awesome, thank you for doing this @jmurphyau!

**Comment by sly7-7** [comment]
@jmurphyau Just updated my app, it's all fine. Thanks again for the update

**Pull request merged**
